<?php

namespace app\controllers\api;

use app\controllers\api\BaseApiController;
use app\models\Post;

class PostController extends BaseApiController
{
    public $modelClass = 'app\models\Post';

    public function actions()
    {
        return parent::actions(); // TODO: Change the autogenerated stub
    }

}